
package Pannel;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/**
 *
 * @author FPTSHOP
 */
public class pnlKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form pnlKhuyenMai
     */
    public pnlKhuyenMai() {
        initComponents();
        radGiaTien.setSelected(true);
        lblViTri3.setVisible(false);
        txtTyLe3.setVisible(false);
        giaTien(txtGiaTien1);
        giaTien(txtGiaTien2);
    }
    public void giaTien(JTextField txt){
         // Lấy Document của JTextField
        PlainDocument doc = (PlainDocument) txt.getDocument();
        // Áp dụng DocumentFilter vào Document của JTextField
        doc.setDocumentFilter(new  FormatNumberFilter ());
    }
public class FormatNumberFilter extends DocumentFilter {
    private static final int MAX_LENGTH = 7; // Độ dài tối đa của số

    @Override
    public void insertString(FilterBypass fb, int offset, String text, AttributeSet attr) throws BadLocationException {
        StringBuilder sb = new StringBuilder();
        sb.append(fb.getDocument().getText(0, fb.getDocument().getLength()));
        sb.insert(offset, text);

        if (isValidNumber(sb.toString())) {
            sb = formatNumber(sb.toString());
            super.insertString(fb, offset, text, attr);
            fb.replace(0, fb.getDocument().getLength(), sb.toString(), attr);
        }
    }

    @Override
    public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
        StringBuilder sb = new StringBuilder();
        sb.append(fb.getDocument().getText(0, fb.getDocument().getLength()));
        sb.replace(offset, offset + length, text);

        if (isValidNumber(sb.toString())) {
            sb = formatNumber(sb.toString());
            super.replace(fb, offset, length, text, attrs);
            fb.replace(0, fb.getDocument().getLength(), sb.toString(), attrs);
        }
    }

    private boolean isValidNumber(String text) {
        return text.matches("\\d*"); // Chỉ cho phép nhập số
    }

    private StringBuilder formatNumber(String number) {
        StringBuilder formattedNumber = new StringBuilder();
        int length = number.length();
        int commaPosition = length % 3;

        for (int i = 0; i < length; i++) {
            if (i > 0 && (length - i) % 3 == commaPosition) {
                formattedNumber.append(",");
            }
            formattedNumber.append(number.charAt(i));
        }

        return formattedNumber;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtTyLe3 = new javax.swing.JTextField();
        lblViTri2 = new javax.swing.JLabel();
        radTyLe = new javax.swing.JRadioButton();
        radGiaTien = new javax.swing.JRadioButton();
        lblViTri1 = new javax.swing.JLabel();
        radSanPham = new javax.swing.JRadioButton();
        lblViTri3 = new javax.swing.JLabel();
        txtGiaTien1 = new javax.swing.JTextField();
        txtGiaTien2 = new javax.swing.JTextField();
        txtTyLe1 = new javax.swing.JTextField();
        txtTyLe2 = new javax.swing.JTextField();
        txtSanPham1 = new javax.swing.JTextField();
        txtSanPham2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itxtTenKhuyenMai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        scrDanhSachSanPhamTimKiem = new javax.swing.JScrollPane();
        tblDanhSachSanPhamTimKiem = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Mã khuyến mãi");

        jLabel3.setText("Tên khuyến mãi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        jLabel7.setText("Tình trạng");

        jLabel11.setText("Ngày bắt đầu");

        jLabel12.setText("Ngày kết thúc");

        jTextField6.setText("jTextField3");

        jLabel6.setText("Chi tiết");

        jTextField7.setText("jTextField3");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTyLe3.setText("vt3");
        jPanel2.add(txtTyLe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 160, -1));

        lblViTri2.setText("Giá trị tối thiểu đơn hàng");
        jPanel2.add(lblViTri2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        btg1.add(radTyLe);
        radTyLe.setText("Tỷ lệ");
        radTyLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTyLeActionPerformed(evt);
            }
        });
        jPanel2.add(radTyLe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btg1.add(radGiaTien);
        radGiaTien.setSelected(true);
        radGiaTien.setText("Giá tiền");
        radGiaTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radGiaTienActionPerformed(evt);
            }
        });
        jPanel2.add(radGiaTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblViTri1.setText("Số tiền giảm");
        jPanel2.add(lblViTri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btg1.add(radSanPham);
        radSanPham.setText("Sản phẩm");
        radSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSanPhamActionPerformed(evt);
            }
        });
        jPanel2.add(radSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblViTri3.setText("jLabel4");
        jPanel2.add(lblViTri3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, -1));

        txtGiaTien1.setText("gt");
        jPanel2.add(txtGiaTien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 160, -1));

        txtGiaTien2.setText("gt");
        jPanel2.add(txtGiaTien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, -1));

        txtTyLe1.setText("gt");
        jPanel2.add(txtTyLe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 160, -1));

        txtTyLe2.setText("gt");
        jPanel2.add(txtTyLe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, -1));

        txtSanPham1.setText("gt");
        jPanel2.add(txtSanPham1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 160, -1));

        txtSanPham2.setText("gt");
        jPanel2.add(txtSanPham2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, -1));

        jLabel5.setText("jLabel5");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        tblDanhSachSanPhamTimKiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Số lượng tồn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachSanPhamTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSanPhamTimKiemMouseClicked(evt);
            }
        });
        scrDanhSachSanPhamTimKiem.setViewportView(tblDanhSachSanPhamTimKiem);

        jButton1.setText("Thêm");

        jButton2.setText("Cập nhật ");

        jButton3.setText("Làm mới");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itxtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(525, 525, 525)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrDanhSachSanPhamTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(55, 55, 55)
                                        .addComponent(jButton2)
                                        .addGap(56, 56, 56)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(97, 97, 97)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itxtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(scrDanhSachSanPhamTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachSanPhamTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSanPhamTimKiemMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_tblDanhSachSanPhamTimKiemMouseClicked

    private void radTyLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTyLeActionPerformed
        // TODO add your handling code here:
        lblViTri1.setText("Phần trăm giảm");
        lblViTri2.setText("Giá trị tối thiểu đơn hàng");
        
        txtGiaTien1.setVisible(false);
        txtGiaTien2.setVisible(false);
        
        txtSanPham1.setVisible(false);
        txtSanPham2.setVisible(false);
        
        lblViTri3.setVisible(true);
        txtTyLe1.setVisible(true);
        txtTyLe2.setVisible(true);
        txtTyLe3.setVisible(true);
        lblViTri3.setText("Giảm tối đa");
    }//GEN-LAST:event_radTyLeActionPerformed

    private void radGiaTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radGiaTienActionPerformed
        // TODO add your handling code here:
        lblViTri1.setText("Số tiền giảm");
        lblViTri2.setText("Giá trị tối thiểu đơn hàng");
        
        txtSanPham1.setVisible(false);
        txtSanPham2.setVisible(false);
        txtTyLe1.setVisible(false);
        txtTyLe2.setVisible(false);
        txtTyLe3.setVisible(false);
        
        txtGiaTien1.setVisible(true);
        txtGiaTien2.setVisible(true);
        
        
    }//GEN-LAST:event_radGiaTienActionPerformed

    private void radSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSanPhamActionPerformed
        // TODO add your handling code here:
        lblViTri2.setText("Số tiền giảm");
        lblViTri1.setText("Tên sản phẩm");
        txtSanPham1.setVisible(true);
        txtSanPham2.setVisible(true);
        txtTyLe1.setVisible(false);
        txtTyLe2.setVisible(false);
        txtTyLe3.setVisible(false);
        
        txtGiaTien1.setVisible(false);
        txtGiaTien2.setVisible(false);
        
    }//GEN-LAST:event_radSanPhamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg1;
    private javax.swing.JTextField itxtTenKhuyenMai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblViTri1;
    private javax.swing.JLabel lblViTri2;
    private javax.swing.JLabel lblViTri3;
    private javax.swing.JRadioButton radGiaTien;
    private javax.swing.JRadioButton radSanPham;
    private javax.swing.JRadioButton radTyLe;
    private javax.swing.JScrollPane scrDanhSachSanPhamTimKiem;
    private javax.swing.JTable tblDanhSachSanPhamTimKiem;
    private javax.swing.JTextField txtGiaTien1;
    private javax.swing.JTextField txtGiaTien2;
    private javax.swing.JTextField txtSanPham1;
    private javax.swing.JTextField txtSanPham2;
    private javax.swing.JTextField txtTyLe1;
    private javax.swing.JTextField txtTyLe2;
    private javax.swing.JTextField txtTyLe3;
    // End of variables declaration//GEN-END:variables
}
