
package Pannel;
import ConnectDB.ConnectDB;
import DAO.NhanVien_DAO;
import Entity.NhanVien;
import Entity.TaiKhoan;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author FPTSHOP
 */
public class pnlTraCuuNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form TraCuuNhanVien
     */
    private TaiKhoan tk;
    private NhanVien_DAO nhanVien_DAO;
    public pnlTraCuuNhanVien(TaiKhoan tk) {
        this.tk = tk;
        initComponents();
        nhanVien_DAO = new NhanVien_DAO();
        init();
        
        
        
    }
    public void init(){
       
		
        addPlaceholderStyle(txtTimKiem);
        ArrayList<NhanVien> dsnv = nhanVien_DAO.layDanhSachNhanVien();
        for (NhanVien nhanVien : dsnv) {
            txtTimKiem.addItemSuggestion(nhanVien.getHoTenNhanVien());
            txtTimKiem.addItemSuggestion(nhanVien.getCCCD());
            txtTimKiem.addItemSuggestion(nhanVien.getSoDienThoai());
            txtTimKiem.addItemSuggestion(nhanVien.getMaNV());
        }
        //txtTimKiem.addItemSuggestion("Ngô Thái Hiệp");
       // txtTimKiem.addItemSuggestion("Phạm Anh Khoa");
       // txtTimKiem.addItemSuggestion("Nguyễn Gia Huy");
       // txtTimKiem.addItemSuggestion("Nguyễn Hồng Huy");
        DuLieuTimKiem();
    }
    public void addPlaceholderStyle(JTextField textFile){
        Font  font = textFile.getFont();
        font = font.deriveFont(Font.ITALIC);
        textFile.setFont(font);
        textFile.setForeground(Color.GRAY);
    }
    public void removePlaceholderStyle(JTextField textFile){
         Font  font = textFile.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textFile.setFont(font);
        textFile.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldSuggestion1 = new ServiceUser.TextFieldSuggestion();
        txtTimKiem = new ServiceUser.TextFieldSuggestion();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtSP = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        txtTimKiem.setText("Tìm kiếm theo mã nhân viên, tên nhân viên");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        jLabel2.setText("Tra cứu nhân viên");

        jButton2.setText("jButton2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ngô", "ba", "phát" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(txtSP, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jButton2)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // TODO add your handling code here:
        if(txtTimKiem.getText().equals("Tìm kiếm theo mã nhân viên, tên nhân viên")){
            txtTimKiem.setText("");
            txtTimKiem.requestFocus();
            removePlaceholderStyle(txtTimKiem);
        }
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        // TODO add your handling code here:
        if(txtTimKiem.getText().length()==0){
            addPlaceholderStyle(txtTimKiem);
            txtTimKiem.setText("Tìm kiếm theo mã nhân viên, tên nhân viên");
        }
    }//GEN-LAST:event_txtTimKiemFocusLost


    private void DuLieuTimKiem(){
       
        txtTimKiem.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                if(!txtTimKiem.getText().equals("") ){
                   txtSP.setText(txtTimKiem.getText());
                    
                }else{
                    // btnDangNhap.setEnabled(false);
                }
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                if( !txtTimKiem.getText().equals("") ){
                   //btnDangNhap.setEnabled(true);
                   txtSP.setText(txtTimKiem.getText());
                }else{
                    // btnDangNhap.setEnabled(false);
                }
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                if( !txtTimKiem.getText().equals("")){
                  txtSP.setText(txtTimKiem.getText());
                    
                }else{
                   //  btnDangNhap.setEnabled(false);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private ServiceUser.TextFieldSuggestion textFieldSuggestion1;
    private javax.swing.JTextField txtSP;
    private ServiceUser.TextFieldSuggestion txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
