
package Pannel;

import Entity.TaiKhoan;
import javax.swing.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
/**
 *
 * @author ThaiHiep
 */
public class pnlTrangChu extends javax.swing.JPanel {

    
    /**
     * Creates new form TrangChu
     */
    private TaiKhoan tk;
    private Timer timer;
    private long startTime;
    private long elapsedTime;
    private  JLabel timJLabel ;
    public pnlTrangChu(TaiKhoan tk, JLabel timJLabel) {
        this.tk= tk;
        this.timJLabel = timJLabel;
        initComponents();
        System.out.println("x"+timJLabel.getText());
        init();
    }
    public void init(){
        System.out.println("X2 : "+timJLabel.getText());
        String timeString = timJLabel.getText(); // Thời gian 01:00:00
        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
        int thoiGianLam = 0;
        try {
            Date parsedTime = format.parse(timeString); // Chuyển đổi chuỗi thời gian thành đối tượng Date
            int hours = parsedTime.getHours(); // Lấy giờ
            int minutes = parsedTime.getMinutes(); // Lấy phút
            int seconds = parsedTime.getSeconds(); // Lấy giây

            System.out.println("Giờ: " + hours);
            System.out.println("Phút: " + minutes);
            System.out.println("Giây: " + seconds);
            thoiGianLam = hours * 60 * 60 * 1000 + minutes * 60 * 1000 + seconds * 1000;
            System.out.println(thoiGianLam);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        startTime = System.currentTimeMillis() - thoiGianLam; // 3600000 milliseconds = 1 giờ

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                long currentTime = System.currentTimeMillis();
                elapsedTime = currentTime - startTime;
                SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                format.setTimeZone(TimeZone.getTimeZone("UTC"));
                String timeText = format.format(new Date(elapsedTime));
                lblThoiGianLam.setText("Thời gian: " + timeText);
            }
        });

        timer.start();


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblThoiGianLam = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        lblThoiGianLam.setText("Thời gian đã làm : ");

        jLabel2.setText("Chức vụ                :");

        jLabel3.setText("jLabel3");

        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThoiGianLam, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblThoiGianLam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblThoiGianLam;
    // End of variables declaration//GEN-END:variables
}
